### PR TITLE
fix(dedup rebuild): if possible, use same backend during rebuild

### LINKED ISSUE #5: Improve rebuild logic
The current rebuild logic is fairly simple: retrieve data, reencode, and send back to the new backends. However, we can check if any of the new backends is also used in the old metadata. If it is, we can assign it the same shard, eliminating the write to that backend, saving some space. 

Need toch check if encoding is deterministic for this, especially if it is a parity shard

### PR DESCRIPTION
**Pull request by iwanbk**
Changes:
- use previous backends if still alive
- Only set the data on the new backends.

Fixes #5

### CODE REVIEW

File: zstor/src/actors/zstor.rs [hunk 1]
```diff
@@ -332,7 +333,31 @@ impl Handler<Rebuild> for ZstorActor {
...
+                let mut used_backends = Vec::new();
+                for (i, data) in existing_data.iter().enumerate() {
+                    let key = old_metadata.shards()[i].key().to_vec();
+                    if let Some(data) = data {
+                        if data.as_slice() == shards[i].as_ref() {
+                            used_backends.push((key, Some(old_metadata.shards()[i].zdb().clone())));
+                            debug!("Shard {} is the SAME", i);
+                        } else {
+                            used_backends.push((key, None));
+                            warn!("Shard {} is DIFFERENT", i);
```
Comment (LeeSmet) [inline zstor/src/actors/zstor.rs:346]: This shouldn't be a warning, not sure if these logs here are needed at all

**Review by LeeSmet — CHANGES_REQUESTED** [review]

File: zstor/src/actors/zstor.rs (hunk 1 above)
Comment (iwanbk) [reply zstor/src/actors/zstor.rs:346]: > not sure if these logs here are needed at all

You're correct for the other two logs:
```rust
debug!("Shard {} is the SAME", i);
debug!("Shard {} is MISSING", i);
```
I can remove it.

But i think the different case is needed and should be a `warn`, because it is unexpected to happens

**Review by LeeSmet — APPROVED** [review]
